#!/bin/sh
# Part of raspi-config https://github.com/luhuadong/yocto-config
#
# See LICENSE file for copyright and license details

INTERACTIVE=True
ASK_TO_REBOOT=0

calc_wt_size() {

	WT_HEIGHT=17
	WT_WIDTH=$(tput cols)

	if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
		WT_WIDTH=80
	fi
	if [ "$WT_WIDTH" -gt 178 ]; then
		WT_WIDTH=120
	fi
	WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

do_finish() {

	exit 0
}

#
# Interactive use loop
#
if [ "$INTERACTIVE" = True ]; then

	calc_wt_size
	while true; do
		
		FUN=$(whiptail --title "i.MX6 Yocto Software Configuration Tool (yocto-config)" --menu "Setup Options" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Finish --ok-button Select \
			"1 Change User Password" "Change password for the current user" \
			"2 Network Options" "Configure network settings" \
			"3 Boot Options" "Configure options for start-up" \
			"4 Localisation Options" "Set up language and regional settings to match your location" \
			"5 Interfacing Options" "Configure connections to peripherals" \
			"6 Overclock" "Configure overclocking for your Pi" \
			"7 Advanced Options" "Configure advanced settings" \
			"8 Update" "Update this tool to the latest version" \
			"9 About yocto-config" "Information about this configuration tool" \
			3>&1 1>&2 2>&3)

		RET=$?
		if [$RET -eq 1 ]; then
			do_finish 
		elif [$RET -eq 0 ]; then
			case "$FUN" in
				1\ *) ;;
				2\ *) ;;
				3\ *) ;;
				4\ *) ;;
				5\ *) ;;
				6\ *) ;;
				7\ *) ;;
				8\ *) ;;
				9\ *) ;;
				*) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1;;
			esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
		else
			exit 1
		fi
	done

fi
